### PR TITLE
show best ips for hiddify next in fragmented format 

### PR DESCRIPTION
**Pull request by ErtebateWeb**
this changes show best ips for hiddify next

### CODE REVIEW

**Comment by ErtebateWeb** [comment]
this script returns :
Endpoint IP:PORT Packet Loss Rate  LOSS Average Delay  DELAY
Endpoint 162.159.192.212:7281 Packet Loss Rate 0.00% Average Delay 352 ms
Endpoint 162.159.195.209:903 Packet Loss Rate 0.00% Average Delay 368 ms
Endpoint 162.159.195.216:903 Packet Loss Rate 0.00% Average Delay 502 ms
Endpoint 188.114.96.39:7281 Packet Loss Rate 10.00% Average Delay 295 ms
Endpoint 188.114.98.4:7281 Packet Loss Rate 10.00% Average Delay 311 ms
Endpoint 188.114.98.110:7281 Packet Loss Rate 10.00% Average Delay 323 ms
Endpoint 162.159.195.111:7281 Packet Loss Rate 10.00% Average Delay 355 ms
Endpoint 188.114.97.184:7281 Packet Loss Rate 10.00% Average Delay 355 ms
Endpoint 162.159.192.107:7281 Packet Loss Rate 10.00% Average Delay 363 ms
Endpoint 188.114.96.93:7281 Packet Loss Rate 10.00% Average Delay 374 ms

Results Saved in result.csv

------------------------------------------
 Best IPv4:Port ---> 162.159.192.212:7281
warp://162.159.192.212:7281/?ifp=5-10
warp://162.159.195.209:903/?ifp=5-10
warp://162.159.195.216:903/?ifp=5-10
warp://188.114.96.39:7281/?ifp=5-10
warp://188.114.98.4:7281/?ifp=5-10
warp://188.114.98.110:7281/?ifp=5-10
warp://188.114.97.184:7281/?ifp=5-10
warp://162.159.195.111:7281/?ifp=5-10
warp://162.159.192.107:7281/?ifp=5-10
warp://188.114.96.93:7281/?ifp=5-10
------------------------------------------

**Comment by Ptechgithub** [comment]
.Thank you for your PR. In my opinion, the optimal format for display is "IP:Port". Additionally, multiple outputs can be a bit confusing.

**Comment by nilofari700** [comment]
win_warp_ip 
من اجرا کردم ولی خروجی یا لیست نمیده چطوری ای پی ها بعد اسکن تحویل بگیرم؟

**Comment by Ptechgithub** [comment]
> win_warp_ip من اجرا کردم ولی خروجی یا لیست نمیده چطوری ای پی ها بعد اسکن تحویل بگیرم؟

اصلاح کردم مجدد دانلود کنید و اجرا کنید.

**Pull request closed without merging**
